// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT btnclick

lv_obj_t * ui_btnclick_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_btnclick;
    cui_btnclick = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_btnclick, 100);
    lv_obj_set_height(cui_btnclick, 50);
    lv_obj_set_x(cui_btnclick, 2);
    lv_obj_set_y(cui_btnclick, 84);
    lv_obj_set_align(cui_btnclick, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_btnclick, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_btnclick, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BTNCLICK_NUM);
    children[UI_COMP_BTNCLICK_BTNCLICK] = cui_btnclick;
    lv_obj_add_event_cb(cui_btnclick, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_btnclick, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_btnclick_create_hook(cui_btnclick);
    return cui_btnclick;
}

