// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_BTNCLICK_H
#define _UI_COMP_BTNCLICK_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT btnclick
#define UI_COMP_BTNCLICK_BTNCLICK 0
#define _UI_COMP_BTNCLICK_NUM 1
lv_obj_t * ui_btnclick_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
